### ISSUE TITLE
there is some slight issue ..

### ISSUE THREAD

**Issue by Gamezpedia** [hendraanggrian/ExpandableLayoutRecyclerView#1]
Hi, i found some glitch , when you expand one item and scroll through the list you will see random items expended [only one item at random indexes] . i am using Android 6.0 , not using any images just texts and buttons only .

thanks.

**Comment by hanggrian** [comment]
@Gamezpedia thanks for the note. I just uploaded version 0.1.2 that addresses this weird behavior. Please try it and let me know how it goes.

**Comment by hendraanggrian** [comment]
@Gamezpedia

**Comment by Gamezpedia** [comment]
Hi, hendraanggrian ! it's working flawlessly good work :+1:  keep it up . and thanks
