### ISSUE TITLE
Migrate to androidx?

### ISSUE THREAD

**Issue by vladkalyuzhny** [hendraanggrian/ExpandableLayoutRecyclerView#4]

**Comment by hanggrian** [comment]
It amazes me that this library is still being used, despite unmaintained for so long. I will update it to AndroidX over the weekend, probably after patching the latest alpha build of AndroidX to [recyclerview-paginated](https://github.com/hendraanggrian/recyclerview-paginated).

Thanks for the reminder!

**Comment by hanggrian** [comment]
Version 0.1 is available under new repository: `com.hendraanggrian.recyclerview:recylcerview-expandable:0.1`. It should be available on jcenter shortly. For now, add `https://dl.bintray.com/hendraanggrian/recyclerview` to your project's repositories.
